import { Camera, RotateCcw, Save, SlidersHorizontal } from "lucide-react";
import type { SimulationMode, SimulationState } from "../types";
import { presets } from "../data/presets";
import { formatNumber } from "../lib/math";
import { metricSummary } from "../lib/relativity";

type Props = { state: SimulationState; setState: (state: SimulationState) => void; onSnapshot: () => void; onSave: () => void };
function RangeControl({ label, value, min, max, step, suffix, onChange }: { label: string; value: number; min: number; max: number; step: number; suffix?: string; onChange: (value: number) => void }) { return <label className="rangeControl"><div><span>{label}</span><strong>{formatNumber(value, 2)}{suffix ?? ""}</strong></div><input type="range" value={value} min={min} max={max} step={step} onChange={(e) => onChange(Number(e.target.value))} /></label>; }
export function ControlPanel({ state, setState, onSnapshot, onSave }: Props) {
  const setMode = (mode: SimulationMode) => setState({ ...state, mode });
  const metrics = metricSummary(state.mass, state.observerRadius, state.spin);
  const dynamicMinRadius = Math.max(54, Math.ceil(metrics.isco + 8));

  return <aside className="panel controlPanel"><div className="panelTitle"><div><p className="eyebrow">Experiment controls</p><h2>Simulation</h2></div><SlidersHorizontal /></div><div className="modeGrid">{(["photon", "cones", "redshift", "time"] as SimulationMode[]).map((mode) => <button key={mode} className={state.mode === mode ? "modeButton active" : "modeButton"} onClick={() => setMode(mode)}>{mode}</button>)}</div><RangeControl label="Black hole mass" value={state.mass} min={1.4} max={7.2} step={0.1} suffix=" M" onChange={(mass) => setState({ ...state, mass })} /><RangeControl label="Observer radius" value={state.observerRadius} min={dynamicMinRadius} max={240} step={1} suffix=" r" onChange={(observerRadius) => setState({ ...state, observerRadius })} /><RangeControl label="Black hole spin" value={state.spin} min={0} max={1} step={0.01} onChange={(spin) => setState({ ...state, spin })} /><small className="mutedText">Raio mínimo acompanha a órbita estável interna (ISCO): {formatNumber(metrics.isco, 1)} r.</small><div className="presetList">{presets.map((preset) => <button key={preset.name} className="presetButton" onClick={() => setState(preset.state)}><strong>{preset.name}</strong><span>{preset.description}</span></button>)}</div><div className="buttonRow triple"><button className="secondaryButton" onClick={() => setState({ mass: 4.8, observerRadius: 150, spin: 0.25, mode: "photon" })}><RotateCcw size={17} />Reset</button><button className="secondaryButton" onClick={onSave}><Save size={17} />Save</button><button className="primaryButton" onClick={onSnapshot}><Camera size={17} />PNG</button></div></aside>;
}